# -*- coding: utf-8 -*-
"""test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zEvU0HKetweSUF2yijuJLZYyn2Suz75Q
"""

import time


fish_list = [
    {"name": "Nemo", "speed": 3},
    {"name": "Dory", "speed": 5},
]


def show_fish_movement_comprehension(fish_list):
    fish_info_list = [(fish['name'], fish['speed']) for fish in fish_list]

    for name, speed in fish_info_list:
        print(f'{name} is swimming at {speed} m/s')
        time.sleep(2)


def show_fish_movement_generator(fish_list):
    for fish in fish_list:
        yield f"{fish['name']} is swimming at {fish['speed']} m/s"
        time.sleep(2)


print("Using Comprehension:")
show_fish_movement_comprehension(fish_list)

print("Using Generator:")
fish_movement_generator = show_fish_movement_generator(fish_list)
for movement_info in fish_movement_generator:
    print(movement_info)